---
name: copy fabrikate generated manifests
on:
  push:
    branches:
      - master

jobs:
  build:
    name: copy manifests
    runs-on: ubuntu-latest
    steps:
      - name: copy manifests
        run: |
          pwd
          ls -al
          ls -al ../
        env:
          SOURCE_DIR: ./generated
          DEST_DIR: ./manifests
