---
name: copy fabrikate generated manifests
on:
  push:
    branches:
      - master

jobs:
  build:
    name: copy manifests
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: copy manifests
        run: |
          cp $SOURCE_DIR $DEST_DIR
          ls -la $DEST_DIR
        env:
          SOURCE_DIR: ./generated/demo
          DEST_DIR: ./manifests
